### ISSUE TITLE
如何按下alt_l键来控制移动速度

### ISSUE THREAD

**Issue by niuxuliang929** [ywsswy/mouseless#1]
Ubuntu18.04亲测可用
linux里还没有一个功能强大的键盘控制鼠标的软件

可以添加一个功能吗？
按下alt_l键来6倍速移动鼠标
我不会写啊

**Comment by ywsswy** [comment]
嗯，常规情况下也没有人会考虑用键盘控制鼠标的，所以这个出于应急使用的目的，没有考虑写得很繁重。
alt键控制加速的功能，我可以单独给你写一个分支，到时候再通知你

**Comment by niuxuliang929** [comment]
okok， 谢谢大哥，这个简直不能太好用啊

**Comment by ywsswy** [comment]
你好，关于alt键加速的功能已添加，欢迎拉最新的代码进行体验，有问题还望及时反馈。
